services:
  honeybee:
    container_name: honeybee
    volumes:
      - ../main.db:/app/main.db
      - ../deploy.txt:/app/deploy.txt
      - ../deploy.log:/app/deploy.log
    tmpfs:
      - /var/lib/varnish:rw,size=1g,exec
    build: .
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production

  postgres:
    image: postgres:latest
    container_name: honeybee_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
